db.music.insertOne({
  _id: "pitanguinha",
  title: "pitanguinha marvada",
  published_at: ISODate('2003-04-16T23:46:31.819Z'),
  year: 2003,
  explicit: true,
  duration: "42:42:42",
  thumbnail_prefix: "thumbnail",
  content_key: "pitanguinha/pitanguinha%20marvada.m4a",
  conversion_status: "SUCCESS",
  artist: "pitanguinha marvada",
  feats: ["pitanguinha", "marvada"],
  album: "pitanguinha marvada stream",
  genre: "BLUES",
  moods: ["CALM"],
})
